# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    influxdb-svc.yaml                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: atrouill <atrouill@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/08 13:43:33 by atrouill          #+#    #+#              #
#    Updated: 2020/12/08 13:43:34 by atrouill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
  - port: 8086
    name: database
    targetPort: 8086
  - port: 8083
    name: pannel
    targetPort: 8083
