# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    influxdb-pvc.yaml                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: atrouill <atrouill@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/04 11:17:46 by atrouill          #+#    #+#              #
#    Updated: 2020/12/04 11:18:03 by atrouill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: influxdb-pvc
  namespace: default
  labels:
    app: influxdb

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
