# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: atrouill <atrouill@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/02 11:13:03 by atrouill          #+#    #+#              #
#    Updated: 2020/12/14 16:18:21 by atrouill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# svc-mariadb.default.svc.cluster.local

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-image
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
              - mysqladmin
              - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
          - name: MYSQL_ADMIN_PASS
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: mysql_admin_pass
          - name: MYSQL_WP_USERPASS
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: mysql_wordpress_user_pass
        volumeMounts:
          - name: mysql-pv
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
