# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: atrouill <atrouill@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/01 17:07:02 by atrouill          #+#    #+#              #
#    Updated: 2020/12/26 18:06:15 by atrouill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
              - /bin/ash
              - livenessprobe.sh
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
          - name: LB_IP
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: loadbalancer_ip
          - name: SSH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pass-secret
                key: ssh_pass
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
