# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps-pvc.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: atrouill <atrouill@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/07 23:19:28 by atrouill          #+#    #+#              #
#    Updated: 2020/12/07 23:19:44 by atrouill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: ftps-pvc
  namespace: default
  labels:
    app: ftps

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
